export const projectData = [
	{
		title: 'The Chronicler',
		languages: 'MySQL, Handlebars, NodeJS',
		liveUrl: 'https://thechronicler.herokuapp.com/',
		gitHubUrl: 'https://github.com/xndrbrgs/the_chronicler',
		img: 'https://i.imgur.com/NUMopwj.png',
		alt: 'A preview of The Chronicler, a group project that utilizes a database of 10,000 books that can be added and saved to a personal library',
		isNew: true,
	},
	{
		title: 'Tech Blog',
		languages: 'JavaScript, SQL, MVC',
		liveUrl: 'https://awidener-tech-blog.herokuapp.com/',
		gitHubUrl: 'https://github.com/awidener3/tech-blog',
		img: 'https://i.imgur.com/JeX8tq6.png',
		alt: 'A preview of the Tech Blog app, an application utilizing SQL to store blog entries',
		isNew: false,
	},
	{
		title: 'fourSTOR',
		languages: 'JavaScript, Foundations',
		liveUrl: 'https://pr1me-e1gh7.github.io/fourstor/',
		gitHubUrl: 'https://github.com/pr1me-e1gh7/fourstor',
		img: 'https://i.imgur.com/BsTHxkt.png',
		alt: 'A preview of fourSTOR, an application utilizing the Yelp! API to retrieve four random businesses based on category in your area',
		isNew: false,
	},
	{
		title: "Grog's Restaurant",
		languages: 'JavaScript, Node.js, Webpack',
		liveUrl: 'https://awidener3.github.io/restaurant-page/',
		gitHubUrl: 'https://github.com/awidener3/restaurant-page',
		img: 'https://i.imgur.com/cCn8yZX.png',
		alt: "A preview of the Grog's restaurant, a single-page webpack application for a fake restaurant",
		isNew: false,
	},
	{
		title: 'Team Profile Generator',
		languages: 'JavaScript, Inquirer, Jest',
		liveUrl: 'https://github.com/awidener3/team-profile-generator',
		gitHubUrl: 'https://github.com/awidener3/team-profile-generator',
		img: 'https://i.imgur.com/A31iAUA.png',
		alt: 'A preview of the Team Profile Generator app, a CLI that allows users to enter information about a development team and receive a generated webpage with that information',
		isNew: false,
	},
	{
		title: "Odin's Library",
		languages: 'HTML, CSS, JavaScript',
		liveUrl: 'https://awidener3.github.io/odin-library/',
		gitHubUrl: 'https://github.com/awidener3/odin-library',
		img: 'https://i.imgur.com/qlTZ8QP.png',
		alt: "A preview of Odin's Library, which uses localStorage to manually add, track, and remove books from your collection",
		isNew: false,
	},
	{
		title: 'Weather Dashboard',
		languages: 'JavaScript',
		liveUrl: 'https://awidener3.github.io/weather-dashboard/',
		gitHubUrl: 'https://github.com/awidener3/weather-dashboard',
		img: 'https://i.imgur.com/Ki5ozRC.png',
		alt: 'A preview of a Weather Dashboard project, which utilizes API calls to a weather API to retrieve current weather in specified areas',
		isNew: false,
	},
];
